default: &default
  adapter: postgresql
  pool: 5
  host: db
  timeout: 5000

development:
  <<: *default
  database: sales_up_development

test:
  <<: *default
  database: sales_up_test

production:
  <<: *default
  database: sales_up_production
