default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: application_development_database

test:
  <<: *default
  database: application_test_database
  host: host_from_database
  username: username_from_database_development
  password: password_from_username_development

production:
  <<: *default
  database: application_production_database
  username: username_from_database_production
  password: password_from_username_production
