default: &default
  adapter: postgresql
  timeout: 5000

development:
  <<: *default
  database: salesup_dev
  host: localhost
  username: pedro_dev
  password: senha123
  pool: 5

test:
  <<: *default

production:
  <<: *default
  database: salesup_dev
  host: localhost
  username: pedro_dev
  password: senha123
  pool: 5
