# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 14871f19adc9fbfd63e39b57f28652798dee33c73c2b78b19f19b341b9b6c9fc9cf2c61383553c6cff2506a94742c9b4f01adc9b41259189d8b95982763038c3

test:
  secret_key_base: 3dc68749025706c8633f4e47a6c8de5d50d966d5bf0c95e7b53e9fa558774c10b08063522337b2403b582c382ffb5c7b704ad7ae6fe9b9c767d7570a0cefd793

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: RAILS_ENV=production rake secret
